repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: ^(la_metro_translation_suite/migrations/)

  - repo: https://github.com/pycqa/flake8
    rev: "9f60881"
    hooks:
      - id: flake8
        exclude: la_metro_translation_suite/migrations
        args: [--max-line-length=88, --extend-ignore=E203]

  - repo: https://github.com/rtts/djhtml
    rev: v1.5.1 # replace with the latest tag on GitHub
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/templates/.*\.html$
        args: [--tabwidth=2] # tabs should be 2 spaces in Django templates

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "1f7d592"
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.19.0
          - eslint-plugin-react@7.30.1
          - eslint-config-prettier@8.5.0

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: ^(la_metro_translation_suite/static/js/lib/|la_metro_translation_suite/static/css/bootstrap|la_metro_translation_suite/templates/)
        files: \.(js|ts|jsx|tsx|css|scss|less|json|markdown|md|yaml|yml)$
